# Generated by Django 5.2.7 on 2025-10-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="inventory_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
