# Generated by Django 5.2.7 on 2025-10-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_artwork_inventory_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="is_print",
            field=models.BooleanField(default=False),
        ),
    ]
