# Generated by Django 5.2.7 on 2025-10-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_artwork_is_print"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="artist",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
